bookshop/Models/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace bookshop.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [StringLength(50)]
        [Display(Name = "Genre")]
        public string GenreName { get; set; }

        public ICollection<BookGenre>? Books { get; set; }
    }
}

bookshop/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using bookshop.Data;
using bookshop.Models;
using bookshop.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace bookshop.Controllers
{
    public class GenresController : Controller
    {
        private readonly BookshopContext _context;

        public GenresController(BookshopContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index(string bookGenre)
        {
            IQueryable<Book> books = _context.Book.AsQueryable();
            IQueryable<string> genreQuery = _context.Genre.Select(x => x.GenreName);

            if(!string.IsNullOrEmpty(bookGenre))
            {
                books = books.Where(x => x.Genres!.Any(x => x.Genre!.GenreName == bookGenre));
            }

            books = books.Include(x => x.Author)
                .Include(x => x.Reviews)
                .Include(x => x.Genres!).ThenInclude(x => x.Genre);

            var bookGenreVM = new BookGenreViewModel
            {
                Genres = new SelectList(await genreQuery.ToListAsync()),
                Books = await books.ToListAsync()
            };

            return View(bookGenreVM);
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(GenreCreateViewModel viewModel) //[Bind("Id,GenreName")] Genre genre
        {
            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel.Genre);
        }

        // GET: Genres/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenreName")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'bookshopContext.Genre'  is null.");
            }

            var bookGenres = await _context.BookGenre.Where(bg => bg.BookId == id).ToListAsync();

            // Remove the records from the context
            _context.BookGenre.RemoveRange(bookGenres);


            var genre = await _context.Genre.FindAsync(id);
            if (genre != null)
            {
                _context.Genre.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genre?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

bookshop/Views/Genres/Create.cshtml
@model bookshop.ViewModels.GenreCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Genre.GenreName" class="control-label"></label>
                <input asp-for="Genre.GenreName" class="form-control" />
                <span asp-validation-for="Genre.GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

bookshop/Views/Genres/Delete.cshtml
@model bookshop.Models.Genre

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

bookshop/Views/Genres/Details.cshtml
@model bookshop.Models.Genre

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

bookshop/Views/Genres/Edit.cshtml
@model bookshop.Models.Genre

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

bookshop/Views/Genres/Index.cshtml
@model bookshop.ViewModels.BookGenreViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Genres" asp-action="Index" method="get">
    <p>
        <select asp-for="BookGenre" asp-items="Model.Genres">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].FrontPage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].YearPublished)
            </th>
            <th>
                Average Rating
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Genres)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Books) {
        <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.FrontPage)*@
                    @if (item.FrontPage != null)
                    {
                        <img src="@item.FrontPage" height="300px" width="190px" asp-append-version="true" />
                    }
                    else
                    {
                        <p>Image not found.</p>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearPublished)
                </td>
                @{
                    var averageRating = item.Reviews?.Count > 0 ? item.Reviews.Average(r => r.Rating) : 0;
                    <td>
                        @String.Format("{0:0.00}", averageRating)
                    </td>
                }

                @{
                    foreach (var genre in item.Genres!)
                    {
                        <td>@genre.Genre!.GenreName</td>
                    }
                }
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                }
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>